# Generated by Django 5.1.4 on 2025-04-15 21:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name_faculty', models.CharField(max_length=50, verbose_name='Название галерее Видео уроков Факультета')),
                ('slug_name_faculty', models.SlugField(unique=True)),
                ('image_faculty', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Название Факультета',
                'verbose_name_plural': 'Название Факультета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video_faculty', models.CharField(max_length=100, verbose_name='Название видиоурока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])], verbose_name='Видеофайл')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='galleryvideo.gallery', verbose_name='Галерея видеоуроков')),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
                'ordering': ['-created_at'],
            },
        ),
    ]
