# Generated by Django 5.2 on 2025-04-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryvideo', '0002_alter_gallery_image_faculty'),
    ]

    operations = [
    ]
