# Generated by Django 5.2 on 2025-04-25 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators



class Migration(migrations.Migration):

    dependencies = [
        ('galleryvideo', '0003_auto_20250425_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название презентации')),
                ('presentation_file', models.FileField(upload_to='presentations/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx', 'ppt'])], verbose_name='Файл презентации')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='galleryvideo.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Презентация',
                'verbose_name_plural': 'Презентации',
                'ordering': ['title'],
            },
        ),

    ]
