# Generated by Django 5.2 on 2025-06-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryvideo', '0006_videotimecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Наименование Карточки темы', 'verbose_name_plural': 'Наименования Карточек тем'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_faculty',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение Видео-уроков'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_name_faculty',
            field=models.CharField(max_length=50, verbose_name='Название галерее Видео-уроков'),
        ),
    ]
