# Generated by Django 5.2 on 2025-06-15 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryvideo', '0007_alter_gallery_options_alter_gallery_image_faculty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Наименование Карточки темы', 'verbose_name_plural': 'Наименование Карточки темы'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='presentation_file',
            field=models.FileField(upload_to='presentations/', validators=[django.core.validators.FileExtensionValidator(['odp', 'pptx', 'ppt', 'pdf'])], verbose_name='Файл презентации'),
        ),
    ]
